apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle-build
spec:
  params:
    - name: gradle-task
      type: string
      description: The gradle task to run
      default: "build"
    - name: gradle-args
      type : string
      description: Extra args (e.g. -x test --stacktrace)
      default: ""
    - name: project-path
      type: string
      default: "gs-spring-boot/complete"
  workspaces:
    - name: source
      description: source code
    - name: gradle-cache
      description: Gradle cache (~/.gradle)
      optional: true
  steps:
    - name: run-gradle
      image: gradle:8.7-jdk17
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        cd "$(workspaces.source.path)/$(params.project-path)"
        ls -alF
        # ./mvnw "$(params.maven-goal)"
        mvn -B "$(params.maven-goal)"
        
