apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: vtw-clone-mvnbuild-pushimage-run
spec:
  pipelineRef:
    name: pipeline-vtwsaas-portal 
  serviceAccountName: tekton-sa 
  params:
    - name: repo-url
      value: "git@github.com:gtno1chun/vtw-saas.git" 
    - name: branch-name
      value: "main"
    - name: maven-goal 
      value: "package"
    - name: image-name 
      value: "docker.io/gtno1chun/vtwsaas" 
    - name: image-tag 
      value: "latest" 
  workspaces:
    - name: shared-workspace 
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: shared-ssh-dir 
      secret:
        secretName: ssh-key-secret
    - name: docker-config 
      secret: 
        secretName: regcred 
