apiVersion: tekton.dev/v1beta1 
kind: Task 
metadata: 
  name: build-and-push-image 
spec:
  params:
    - name: image-name 
      type: string 
      description: The name of the image to build and push 
    - name: image-tag
      type: string 
      description: The tag for the image (e.g., latest, v1.0). 
      default: "latest"
    - name: dockerfile-path 
      type: string 
      default: "gs-spring-boot/complete"  
  workspaces:
    - name: source 
      description: The workspace containing the source code and Dockerfile. 
    - name: docker-config 
      description: The workspace for Docker credentials 
  steps:
    - name: create-docker-config
      image: alpine:latest
      env:
        - name: DOCKER_CONFIG_JSON
          valueFrom:
            secretKeyRef:
              name: regcred
              key: .dockerconfigjson
      script: |
        #!/bin/sh
        # writable /kaniko/.docker directory is not guaranteed to be writable
        mkdir -p /tekton/home/.docker
        echo "${DOCKER_CONFIG_JSON}" > /tekton/home/.docker/config.json 
        ls -al /tekton/home/.docker
        cat /tekton/home/.docker/config.json 
    - name: build-and-push 
      image: gcr.io/kaniko-project/executor:latest 
      env:
        - name: DOCKER_CONFIG 
          value: /tekton/home/.docker
        # - name: USERNAME
        #   valueFrom:
        #     secretKeyRef: 
        #       name: regcred 
        #       key: username
        # - name: PASSWORD 
        #   valueFrom:
        #     secretKeyRef:
        #       name: regcred 
        #       key: password 
      args:
        - --dockerfile=$(workspaces.source.path)/$(params.dockerfile-path)/Dockerfile
        - --context=dir://$(workspaces.source.path)/$(params.dockerfile-path)
        - --destination=$(params.image-name):$(params.image-tag)
        # - --insecure=false 
