apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded docker config>
# <base64-encoded docker config>는 base64 -w0 ~/.docker/config.json 값을 넣으면 됨