apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-pipeline-vtwsaas-portal
spec:
  params:
    - name: repo-url
      type: string
      description: SSH URL of the repository
      default: ""
    - name: branch-name
      type: string
      default: "main"
    - name: project-path
      type: string
      description: path to Node.js app (contains package.json & Dockerfile)
      default: "gs-nodejs/servers/express/api-with-express-and-handlebars"
    - name: build-command
      type: string
      default: "npm run build"
    - name: image-name
      type: string
      description: full image name (e.g., docker.io/user/repo)
      default: ""
    - name: image-tag
      type: string
      default: "latest"
  workspaces:
    - name: shared-workspace
    - name: shared-ssh-dir
    - name: docker-config
    - name: node-cache
      optional: true
  tasks:
    - name: clone
      taskRef: { name: git-clone-ssh-nodejs }
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: branch-name
          value: $(params.branch-name)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: ssh-dir
          workspace: shared-ssh-dir

    - name: build
      runAfter: ["clone"]
      taskRef: { name: nodejs-build }
      params:
        - name: project-path
          value: $(params.project-path)
        - name: build-command
          value: $(params.build-command)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: node-cache
          workspace: node-cache

    - name: image
      runAfter: ["build"]
      taskRef: { name: build-and-push-image-nodejs }
      params:
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
        - name: dockerfile-path
          value: $(params.project-path)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: docker-config
          workspace: docker-config
