apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: vtw-nodejs-clone-build-push-run
  namespace: default
spec:
  pipelineRef:
    name: nodejs-pipeline-vtwsaas-portal
  serviceAccountName: tekton-sa
  params:
    - name: repo-url
      value: "git@github.com:noome7777/Tekton-CI-CD.git"
    - name: branch-name
      value: "main"
    - name: project-path
      value: "gs-nodejs/servers/express/api-with-express-and-handlebars"
    - name: build-command
      value: ""                        # CHANGED: 장기 실행 방지(빈 값으로)
    - name: image-name
      value: "docker.io/chulsune123/tekton-ci-cd"
    - name: image-tag
      value: "nodejs" #latest로 수정 해도 됨!
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    - name: shared-ssh-dir
      secret:
        secretName: ssh-key-secret
        items:
          - key: ssh-key
            path: ssh-key
    - name: docker-config
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: node-cache
      emptyDir: {}