apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-ssh-nodejs
spec:
  params:
    - name: repo-url
      type: string
      description: SSH URL of the repository
    - name: branch-name
      type: string
      default: "main"
    - name: install-command
      type: string
      default: "npm ci"
  workspaces:
    - name: source
    - name: ssh-dir
  steps:
    - name: clone
      image: alpine/git:v2.49.1
      script: |
        #!/bin/sh
        set -eu
        mkdir -p /root/.ssh
        cp $(workspaces.ssh-dir.path)/ssh-key /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        echo "StrictHostKeyChecking no" >> /root/.ssh/config
        git clone "$(params.repo-url)" "$(workspaces.source.path)"
        cd "$(workspaces.source.path)"
        git checkout "$(params.branch-name)"
    - name: npm-install
      image: node:18-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -eu
        if [ -f package.json ]; then
          $(params.install-command)
        fi
