apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-image-nodejs
spec:
  params:
    - name: image-name
      type: string
    - name: image-tag
      type: string
      default: "latest"
    - name: dockerfile-path
      type: string
      default: "servers/express/api-with-express-and-handlebars"
    - name: extra-args
      type: string
      default: ""
  workspaces:
    - name: source
    - name: docker-config
  steps:
    - name: whoami
      image: alpine:3.20
      env:
        - name: DOCKER_CONFIG
          value: $(workspaces.docker-config.path)
      script: |
        #!/bin/sh
        set -eu
        CFG="$DOCKER_CONFIG/config.json"
        if [ ! -f "$CFG" ]; then
          echo "ERROR: $CFG not found"; exit 1
        fi
        USER_IN_CFG=$(sed -n 's/.*"auth"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$CFG" \
          | head -n1 | base64 -d 2>/dev/null | cut -d: -f1 || true)
        echo "Docker user in config: ${USER_IN_CFG:-UNKNOWN}"
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: DOCKER_CONFIG
          value: $(workspaces.docker-config.path)
      args:
        - --dockerfile=$(workspaces.source.path)/$(params.dockerfile-path)/Dockerfile
        - --context=$(workspaces.source.path)/$(params.dockerfile-path)
        - --destination=$(params.image-name):$(params.image-tag)
        - $(params.extra-args)
